### PR TITLE
Support host names

### PR DESCRIPTION
**Pull request by madsbk**
Fixes issue #430

### CODE REVIEW

**Comment by pentschev** [comment]
Wow, that was quick! Thanks @madsbk , I'm sure @randerzander will appreciate it.

**Comment by pentschev** [comment]
rerun tests

**Comment by quasiben** [comment]
We are working on the fix for distributed -- alternatively, we can comment out the cupy test while we sort out issues:
https://github.com/rapidsai/ucx-py/blob/branch-0.13/ci/gpu/build.sh#L134

**Comment by pentschev** [comment]
If you think this will take another day or two only, I think we can wait instead of removing tests. It's not critical since we can still use IP addresses.

**Comment by jakirkham** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
