### PR TITLE
Debugging CI segfault

### PR DESCRIPTION
**Pull request by madsbk**
This PR is a fork of 7b739a48dc4b647edd7234424e2dd94720606c86, which is from the 7th October.

The CI test `gpuCI/ucx-py/gpu-test/centos7-cuda10.0` segfault. 

@jakirkham @quasiben, has something changed in the CI setup that could trigger this?

### CODE REVIEW

**Comment by quasiben** [comment]
On a DGX all tests pass but I do see the following:

```

tests/test_shutdown.py::test_listener_close PASSEDERROR Ignored except: <class 'str'> Task was destroyed but it is pending!

tests/test_shutdown.py::test_listener_del PASSEDERROR Ignored except: <class 'str'> Task was destroyed but it is pending!

tests/test_ucx_getters.py::test_get_ucp_worker PASSED
tests/test_ucx_getters.py::test_get_endpoint PASSED
tests/test_version.py::test_get_ucx_version PASSED
tests/test_version.py::test_version_constant PASSED
tests/test_version.py::test_ucx_version_constant PASSED

======================================================================================================================= 101 passed in 58.28s ========================================================================================================================
[1571686847.789503] [dgx15:67868:0]          mpool.c:43   UCX  WARN  object 0x562b3713ae80 was not returned to mpool ucp_am_bufs
[1571686847.789518] [dgx15:67868:0]          mpool.c:43   UCX  WARN  object 0x562b3715af00 was not returned to mpool ucp_am_bufs
[1571686847.793705] [dgx15:67868:0]          mpool.c:43   UCX  WARN  object 0x562b35c6e600 was not returned to mpool ucp_requests
[1571686847.793712] [dgx15:67868:0]          mpool.c:43   UCX  WARN  object 0x562b35c6e740 was not returned to mpool ucp_requests
[1571686847.793714] [dgx15:67868:0]          mpool.c:43   UCX  WARN  object 0x562b35c6e880 was not returned to mpool ucp_requests
[1571686847.793717] [dgx15:67868:0]          mpool.c:43   UCX  WARN  object 0x562b35c6e9c0 was not returned to mpool ucp_requests
[1571686847.793719] [dgx15:67868:0]          mpool.c:43   UCX  WARN  object 0x562b35c6eb00 wa
....
[1571686847.795920] [dgx15:67868:0]          async.c:353  UCX  WARN  async 0x562b1c476938 handler 0x562b35c085b0 [id=87] ???() ???() not released
[1571686847.795926] [dgx15:67868:0]          async.c:353  UCX  WARN  async 0x562b1c476938 handler 0x562b35c744c0 [id=854] ???() ???() not released
[1571686847.795933] [dgx15:67868:0]          async.c:353  UCX  WARN  async 0x562b1c476938 handler 0x7fbb8c0029b0 [id=864] ???() ???() not released
[1571686847.795938] [dgx15:67868:0]          async.c:353  UCX  WARN  async 0x562b1c476938 handler 0x7fbb8c000d10 [id=850] ???() ???() not released
[1571686847.795942] [dgx15:67868:0]          async.c:354  UCX  WARN  releasing async context with 4 handlers
```

**Comment by madsbk** [comment]
The `was not returned to mpool ucp_am_bufs` and `Ignored except: <class 'str'> Task was destroyed but it is pending!` warnings should get fixed in https://github.com/rapidsai/ucx-py/pull/289

The tests also works on `ubuntu16.04-cuda9.2`  and `ubuntu18.04-cuda10.1` but `centos7-cuda10.0` segfaults. @quasiben @jakirkham do you know if the `centos7-cuda10.0` setup has changed since last week?

**Comment by quasiben** [comment]
I don't think the env has changed.  I believe this docker image metadata is managed here:
https://github.com/rapidsai/gpuci-build-environment and hasn't had an update in over 2 weeks

**Comment by quasiben** [comment]
rerun

**Comment by quasiben** [comment]
rerun tests

**Comment by quasiben** [comment]
I am able to reproduce the segfault with latest UCX master.  Previously I was using `4042503042ac9132bb505dd675d93b506eb868f7` which was from Oct 14th.

**Comment by quasiben** [comment]
Wait, maybe this is a different segfault (and it happens after everything has passed):

```
tests/test_version.py::test_ucx_version_constant PASSED

================================================================================================= 101 passed in 51.20s =================================================================================================
Traceback (most recent call last):
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf_dev10.1/lib/python3.7/asyncio/base_events.py", line 688, in call_soon
    self._check_closed()
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf_dev10.1/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: 'ucp._libs.send_recv._tag_recv_callback'
Traceback (most recent call last):
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf_dev10.1/lib/python3.7/asyncio/base_events.py", line 688, in call_soon
    self._check_closed()
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf_dev10.1/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Fatal Python error: Segmentation fault
````

**Comment by quasiben** [comment]
@madsbk see https://github.com/rapidsai/ucx-py/pull/291 -- tests are all passing but with a caveat around `ucp.reset()` in one of the tests

**Comment by quasiben** [comment]
with https://github.com/rapidsai/ucx-py/pull/289 we can close this

**Pull request closed without merging**
