### PR TITLE
Run PyTorch tests from Distributed on CI

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure we are running the PyTorch tests on CI so we can catch any regressions here.

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Looks like we are running into [conflicts with `cmake`]( https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/ucx-py/job/prb/job/ucx-py-gpu-build/2161/display/redirect ), which it turns out we don't need. Submitted PR ( https://github.com/rapidsai/ucx-py/pull/570 ) to drop `cmake` and clean-up our CI requirements in the interim.

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
Oh, now I see the cmake conflict, first time I missed it and tried rerunning, we'll really need to wait for #570 .

**Comment by jakirkham** [comment]
rerun tests

**Pull request merged**
