### PR TITLE
Drop the `Makefile`

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/rapidsai/ucx-py/issues/256

As the build process has been simplified considerably and the content in this `Makefile` seems to be going out-of-date anyways, go ahead and drop it in favor of more standard Python build and install mechanisms.

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by quasiben** [comment]
This is still failing to find UCX_PATH.  Do we no longer have to prepend LDFLAGS and CFLAGS during build_ext ?

Something like the following in setup.py

```python
UCX_PATH = os.environ['UCX_PATH']
CUDA_PATH = os.environ['CUDA_PATH']
CFLAGS  = "-I%s/include -I%s/include" % (UCX_PATH, CUDA_PATH)
LDFLAGS = "-L%s/lib -L%s/lib64" % (UCX_PATH, CUDA_PATH)
extra_compile_args.extend([CFLAGS, LDFLAGS])
```

**Comment by jakirkham** [comment]
Yeah this needs more work for sure. Thought I had things figured out initially, but ran into a few surprises with CI. So have tried to sort that out with the subsequent commits. Will revisit this one tomorrow. 🙂

**Comment by quasiben** [comment]
Cool!  Lots of neat tricks in those other PRs.  Didn't know about `get_config_var('LIBDIR')`

**Comment by jakirkham** [comment]
> Cool! Lots of neat tricks in those other PRs. Didn't know about `get_config_var('LIBDIR')`

Yeah I learned that one a while back when wresting with building Python extensions.

**Pull request merged**
