### PR TITLE
Add local-send-recv benchmark using core library only

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by pentschev** [comment]
@madsbk this is based on your idea during our conversation earlier this week, a benchmark that's entirely built on the core library. Would you mind taking a look?

@quasiben also tagging you in case you'd like to take a look as well.

**Review by madsbk — APPROVED** [review]
LGTM but I think we should remove the `local-` prefix from the names of the `local-send-recv` benchmarks. 
The `local-` prefix is from before they supported running on multiple nodes.

**Comment by pentschev** [comment]
> LGTM but I think we should remove the `local-` prefix from the names of the `local-send-recv` benchmarks.
> The `local-` prefix is from before they supported running on multiple nodes.

Agreed, this was something that was bugging me as well. Removed the prefix now.

**Review by ajschmidt8 — APPROVED** [review]
Approving `ops-codeowner` file changes

**Comment by pentschev** [comment]
Thanks @madsbk and @ajschmidt8 for the reviews!

**Pull request merged**
