### PR TITLE
[DRAFT] Add Examples

### PR DESCRIPTION
**Pull request by quasiben**
cc @jakirkham

### CODE REVIEW

**Comment by pentschev** [comment]
LGTM.

**Comment by jakirkham** [comment]
Would it be possible to run these examples in CI?

**Comment by pentschev** [comment]
Today CI is limited to a single GPU. Even if possible, I wonder about the extent of usefulness of this for now.

**Comment by jakirkham** [comment]
The example? It's useful for people starting out with this package. It can be a nice verification that things got installed/configured correctly. Or a nice jumping off point for more complex code that uses this pattern.

The main concern I have with excluding this example from CI testing is that it is likely to go stale given the rapid rate of change in the library.

**Comment by quasiben** [comment]
We could run this as part of CI but as @pentschev said we are currently limited to one GPU.   @jakirkham is that something you could take a look at ?  Possibly ping on this issue https://github.com/rapidsai/ops/issues/504 ?

**Comment by pentschev** [comment]
My comment may have been a bit misleading, what I mean is that currently it's probably possible to run the example on CI, but given it's limited to a single GPU, I don't think that would be too useful for now (before we have multi-GPU support).

**Comment by jakirkham** [comment]
Certainly it would be beneficial to have the ideal environment to test on, but there is even value in just running the code in a non-ideal environment. It will help us catch functions that have been changed or dropped and forces us to handle these changes in the example somehow.

**Comment by jakirkham** [comment]
Raised the CI testing point as issue ( https://github.com/rapidsai/ucx-py/issues/308 ).

**Comment by jakirkham** [comment]
Thanks @quasiben!

**Pull request merged**
