### PR TITLE
Drop the conda recipes from this repo

### PR DESCRIPTION
**Pull request by jakirkham**
As these recipes have been supplanted by the recipes in the feedstock in conda-forge, go ahead and drop them from ucx-py.

ref: https://github.com/conda-forge/ucx-split-feedstock

### CODE REVIEW

**Comment by quasiben** [comment]
@jakirkham should we merge this before we have the solution for building new conda packages in place ?

**Comment by jakirkham** [comment]
The recipes here are outdated. It would be good to get rid of this outdated information to avoid confusion.

**Comment by jakirkham** [comment]
@quasiben, any other thoughts? I'm inclined to merge this.

**Comment by quasiben** [comment]
nope, sorry forgot to press the green button.  Thanks @jakirkham !

**Comment by jakirkham** [comment]
No worries. Thanks!

**Pull request merged**
