### PR TITLE
Use UCX-Py in docs [skip ci]

### PR DESCRIPTION
**Pull request by quasiben**
PR corrects naming style of UCX-Py

cc @pentschev

### CODE REVIEW

**Comment by pentschev** [comment]
Failure here is in distributed, just like I mentioned in https://github.com/rapidsai/ucx-py/pull/538#issuecomment-638080285 .

**Comment by quasiben** [comment]
> Thanks @quasiben . For future reference, in docs-only PR we can add [skip ci] as a suffix to the title of the PR to avoid building. :)

Thanks, forgot about this feature

**Comment by jakirkham** [comment]
> Failure here is in distributed, just like I mentioned in [#538 (comment)](https://github.com/rapidsai/ucx-py/pull/538#issuecomment-638080285) .

Added PR ( https://github.com/rapidsai/cudf/pull/5379 ) to cuDF to fix the Distributed test failure. Have confirmed this fixes the issue locally as well.

**Comment by quasiben** [comment]
thank you John!

**Comment by quasiben** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Pull request merged**
