### PR TITLE
Support CUDA 12.0 for pip wheels

### PR DESCRIPTION
**Pull request by divyegala**

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
LGTM, thanks @divyegala !

**Review by ajschmidt8 — APPROVED** [review]

**Comment by divyegala** [comment]
> Also I see cudf in the test requirements but I’m not sure what is happening since I don’t see it being installed

Looks like the tests that require `cudf` are not being run for wheels

**Comment by divyegala** [comment]
@bdice looks like now we are installing both `cupy-cuda11x` and later `cupy-cuda12x` in the `arm64` job. Not quite sure what's going on here

**Review by jakirkham — APPROVED** [review]

**Pull request merged**
