### PR TITLE
Drop hard numpy requirement

### PR DESCRIPTION
**Pull request by jakirkham**
This reworks PR ( https://github.com/rapidsai/ucx-py/pull/120 )'s changes slightly to drop the hard NumPy requirement added by it. Fixing an issue encountered when building the ucx-py packages.

### CODE REVIEW

**Comment by jakirkham** [comment]
Does this change still work for your use case, @mrocklin?

**Comment by mrocklin** [comment]
It seems to be equivalent, but I no longer have a solid test.  I say merge at will.

**Comment by jakirkham** [comment]
Thanks Matt! 😄

**Comment by pentschev** [comment]
Hmmm, I'm not sure exactly why/if ucx-py really requires NumPy, but using the new ucx-py conda package from @jakirkham fails to load `ucp` because of missing NumPy:

```python
>>> import ucp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/pentschev/src/ucx-py/ucp/__init__.py", line 2, in <module>
    from ._libs.ucp_py import *  # noqa
  File "ucp/_libs/ucp_py_buffer_helper.pyx", line 12, in init ucp_py
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by TomAugspurger** [comment]
Just checking: did you rebuild your extensions?

**Comment by jakirkham** [comment]
@pentschev, that seems to be referring to the `import` this patch removed. The packages also contain this change. Are you sure this isn’t coming from a local install from previous experimentation?

In any event, I agree we could use some clarity on ucx-py’s requirements. Raised issue ( https://github.com/rapidsai/ucx-py/issues/146 ) on this point. Hopefully others can fill in any details we are missing.

**Comment by jakirkham** [comment]
Yeah I should regenerate the Cythonized C files here too. Though the packages used the Cython code directly. So I think we still shouldn’t be seeing this error.

**Comment by pentschev** [comment]
Indeed, there was something strange with my conda install lately, after installing new packages to the environment they're not always reflected until I open a new shell session. I cleaned it up and now it works. Thanks for the help!

**Comment by jakirkham** [comment]
No worries. Glad to hear things are working correctly now 🙂

**Pull request merged**
