### PR TITLE
Update serialization code in benchmarks

### PR DESCRIPTION
**Pull request by galipremsagar**
This PR fixes failures seen in https://github.com/rapidsai/ucx-py/actions/runs/12271127951

### CODE REVIEW

**Review by quasiben — APPROVED** [review]
Thanks @galipremsagar

**Comment by jakirkham** [comment]
Thanks Prem and Ben! 🙏

Would have suggested the exact same change 😄

**Comment by galipremsagar** [comment]
> Thanks Prem! 🙏
> 
> Looks like 0.41 was just released ( #1095 ). Do we want to move this to 0.42?
> 
> Requesting changes to avoid accidental merge while discussing

Moved to 0.42.

**Pull request merged**
