### PR TITLE
More Information on Communication Error

### PR DESCRIPTION
**Pull request by madsbk**
This PR adds extra information on communication error, which easy debugging.
And adds message length checks.

### CODE REVIEW

**Comment by quasiben** [comment]
@madsbk do you know of any way we can generate/force a communication error ?

**Comment by madsbk** [comment]
> @madsbk do you know of any way we can generate/force a communication error ?

Yes, I have added length mismatch test.

**Comment by quasiben** [comment]
Thanks @madsbk !

**Comment by jakirkham** [comment]
I guess we are waiting on PR ( https://github.com/rapidsai/ucx-py/pull/247 ) then.

**Comment by quasiben** [comment]
I think we should merge #247 and reformat if Matt B. has more thoughts

**Pull request merged**
