### PR TITLE
Use RMM's DeviceBuffer (in cudf-merge and elsewhere)

### PR DESCRIPTION
**Pull request by jakirkham**
Use RMM `DeviceBuffer` for allocations.

### CODE REVIEW

**Comment by jakirkham** [comment]
For both of the following, ran this command on latest nightlies:

```
UCXPY_IFNAME="enp1s0f0" UCX_TLS=tcp,cuda_copy,sockcm python ucx-py/benchmarks/cudf-merge.py --chunks-per-dev 4 --chunk-size 10000 --rmm-init-pool-size 100
```

Without this change I see this performance:

```
cudf merge benchmark
----------------------------
device(s)      | [0]
chunks-per-dev | 4
rows-per-chunk | 10000
data-processed | 1.28 MB
frac-match     | 0.3
============================
Wall-clock     | 48.53 ms
Bandwidth      | 11.62 MB/s
Throughput     | 26.38 MB/s
```

With this change I see this performance:

```
cudf merge benchmark
----------------------------
device(s)      | [0]
chunks-per-dev | 4
rows-per-chunk | 10000
data-processed | 1.28 MB
frac-match     | 0.3
============================
Wall-clock     | 42.80 ms
Bandwidth      | 16.21 MB/s
Throughput     | 29.91 MB/s
```

**Comment by pentschev** [comment]
@jakirkham could you also share results for larger problems (perhaps increasing `chunks-per-dev` or `rows-per-chunk`, or maybe both)?

I see a gain of performance here, but I'm not sure I understand why that happens and how you came to the conclusion that replacing RMM for CuPy would have that effect. Could you elaborate on that?

**Comment by jakirkham** [comment]
Just for clarity both cases are [allocating through RMM]( https://github.com/rapidsai/ucx-py/blob/593fc8d7d1e4b9997be0816466b7ed9a27c53cef/benchmarks/cudf-merge.py#L172-L173 ). It's just a difference in APIs. Am making this change w.r.t. the discussion in issue ( https://github.com/rapidsai/rmm/issues/180 ) to remove this API from RMM.

That said, I was curious of the performance impact. So ran things to see. Agree it is not big (nor would I expect it to be). I don't expect there to be a particularly noticeable scale difference as we are using the same underlying allocator.

**Comment by pentschev** [comment]
Thanks for the info @jakirkham .

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Comment by madsbk** [comment]
Nice work @jakirkham

**Pull request merged**
