### PR TITLE
Move debug-tests outside of tests

### PR DESCRIPTION
**Pull request by pentschev**
This is probably a better alternative for debug-tests, this way we prevent users from running debug tests and developers from accidentally ignoring critical tests that need fixing.

cc @jakirkham

### CODE REVIEW

**Comment by pentschev** [comment]
Also sorry @jakirkham for merging your PR and immediately after suggesting reverting it.

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Pull request merged**
