### PR TITLE
Update UCP configuration validation tests for UCX >= 1.12

### PR DESCRIPTION
**Pull request by pentschev**
Starting from UCX 1.12, it's not possible to validate non-UCP configuration options, update tests accordingly.

See https://github.com/openucx/ucx/issues/7519 .

### CODE REVIEW

**Comment by quasiben** [comment]
We can merge when tests pass

**Comment by jakirkham** [comment]
@gpucibot rerun tests

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by pentschev** [comment]
Thanks @quasiben and @jakirkham for reviews!

**Comment by jakirkham** [comment]
Thanks Peter for the update!

**Pull request merged**
