### PR TITLE
Compiling with compile flag "-Werror"

### PR DESCRIPTION
**Pull request by madsbk**
This PR lets CI fail on compile warnings and fixes all current warnings.

### CODE REVIEW

**Comment by pentschev** [comment]
Good idea!

**Comment by pentschev** [comment]
That works, we'll need to merge https://github.com/rapidsai/ucx-py/pull/713 before this passes.

**Comment by madsbk** [comment]
> That works, we'll need to merge #713 before this passes.

Didn't see that PR. Yeah, let's get that in first.

**Comment by pentschev** [comment]
> > That works, we'll need to merge #713 before this passes.
> 
> Didn't see that PR. Yeah, let's get that in first.

No worries, if you prefer, we can do all the changes here and close that, it doesn't matter for me.

**Comment by pentschev** [comment]
rerun tests

**Review by pentschev — APPROVED** [review]
LGTM, thanks Mads!

**Pull request merged**
