### PR TITLE
Pass `size` as keyword argument to `DeviceBuffer`

### PR DESCRIPTION
**Pull request by jakirkham**
As `DeviceBuffer` requires arguments passed to its constructor are keyword arguments, make sure to pass `size` as a keyword argument as well.

### CODE REVIEW

**Comment by madsbk** [comment]
rerun tests

**Comment by quasiben** [comment]
The tests are all failing in the same spot:

```

>               raise exceptions.UCXError(msg)

E               ucp.exceptions.UCXError: Trying to reset UCX but not all Endpoints and/or Listeners are closed(). The following objects are still referencing ApplicationContext: 

E                 <ucp._libs.core._Listener object at 0x7fa0739dd360>

E                 {'_ucp_endpoint': 140327189295176, '_ucp_worker': 94357455191360, '_ctx': <ucp._libs.core.ApplicationContext object at 0x7fa0739dd440>, '_msg_tag_send': 202377539546448721, '_msg_tag_recv': 396299786812252552, '_ctrl_tag_send': 791187273453251718, '_ctrl_tag_recv': 1308621401097336308, '_guarantee_msg_order': True, '_send_count': 0, '_recv_count': 0, '_finished_recv_count': 0, '_closed': False, 'pending_msg_list': [{'log': '[Recv shutdown] ep: 0x7fa078453048, tag: 0x1229283b1de175f4', 'future': <Future pending cb=[handle_ctrl_msg(<weakref at 0...x7fa07394ba50>, '[Recv shutdo...9283b1de175f4', <ucp._libs.co...x7fa073fd0210>)()]>, 'ucp_request': 94357463643048, 'expected_receive': 16}], '_cuda_support': True, '_close_after_n_recv': None}

E                 {'_ucp_endpoint': 140327189295248, '_ucp_worker': 94357455191360, '_ctx': <ucp._libs.core.ApplicationContext object at 0x7fa0739dd440>, '_msg_tag_send': 396299786812252552, '_msg_tag_recv': 202377539546448721, '_ctrl_tag_send': 1308621401097336308, '_ctrl_tag_recv': 791187273453251718, '_guarantee_msg_order': True, '_send_count': 0, '_recv_count': 0, '_finished_recv_count': 0, '_closed': False, 'pending_msg_list': [{'log': '[Recv shutdown] ep: 0x7fa078453090, tag: 0xafadca220fdac86', 'future': <Future pending cb=[handle_ctrl_msg(<weakref at 0...x7fa07394ba90>, '[Recv shutdo...adca220fdac86', <ucp._libs.co...x7fa073fd0410>)()]>, 'ucp_request': 94357463643368, 'expected_receive': 16}], '_cuda_support': True, '_close_after_n_recv': None}



ucp/public_api.py:204: UCXError

=============================== warnings summary ===============================

tests/test_custom_send_recv.py::test_send_recv_cudf[<lambda>2]

  /conda/envs/gdf/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

    return f(*args, **kwds)
```

could this be related to the new ucx 1.7.0rc2 release ?

**Comment by jakirkham** [comment]
> could this be related to the new ucx 1.7.0rc2 release ?

Were new packages of this built automatically? If not, I don't think so.

**Comment by jakirkham** [comment]
Did something change about the machine that is used to run the CI?

**Comment by quasiben** [comment]
it looks like 1.7.0rc2 is now a conda package:
`9d06c3a` is the latest commit hash:
https://github.com/openucx/ucx/tree/v1.7.x

and that is the hash on anaconda.org:
https://anaconda.org/rapidsai-nightly/ucx/files

**Comment by jakirkham** [comment]
It sounds like you are saying they are being automatically built somehow. Then yes that could be an issue.

Though IDK if we should worry about 1.7.0rc2 when we should be building 1.7.0. ( https://github.com/rapidsai/ucx-split-feedstock/pull/7 ) Do we know when those changes will be picked up in the Conda package builds?

**Comment by pentschev** [comment]
It seems like v1.7.0 has the same hash as rc2: https://github.com/openucx/ucx/releases/tag/v1.7.0 .

**Comment by pentschev** [comment]
Actually, looking at tags, the hashes are different, and the one we're building is indeed v1.7.0 (not rc2): https://github.com/openucx/ucx/tags .

**Comment by quasiben** [comment]
> Actually, looking at tags, the hashes are different, and the one we're building is indeed v1.7.0 (not rc2): https://github.com/openucx/ucx/tags .

yes, you are right.   sorry for the noise

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Have been seeing some install issues. Restarting has helped, but hasn't given us an all green yet.

**Comment by quasiben** [comment]
Thanks @jakirkham for getting this in

**Pull request merged**
