### PR TITLE
Fix import in debug-tests

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by pentschev** [comment]
Sorry for the overwhelmingly long PR, I hope I don't destroy anyone's day with all the time it will take reviewing it.

**Comment by pentschev** [comment]
And still I managed to screw up formatting. 🤦

**Comment by jakirkham** [comment]
Thanks Peter! 😄

**Comment by pentschev** [comment]
Thanks @jakirkham for approving, I hope it didn't take too much of your time. 😄

**Pull request merged**
