### PR TITLE
Refactoring: merging public_api.py => core.py

### PR DESCRIPTION
**Pull request by madsbk**
Merging `public_api.py => core.py`. No behavior change.

### CODE REVIEW

**Comment by jakirkham** [comment]
@cjnolet @pentschev, could you please also take a look? 🙂

**Comment by quasiben** [comment]
@cjnolet you should be aware of these changes in as this may cause breakages in cuML if there are any dependencies on `public_api`

**Comment by cjnolet** [comment]
@quasiben and @jakirkham, I definitely appreciate the heads up. At first glance, it doesn't seem like there should be any changes to the user-facing API, but I'll run cuML's UCX tests against it to be sure.

**Comment by jakirkham** [comment]
Please let us know once you do 🙂

**Comment by jakirkham** [comment]
Thanks Mads! 😄

**Comment by cjnolet** [comment]
@quasiben @jakirkham @madsbk, I installed the nightly and verified our tests that make use of ucx-py still work on >1 GPUs.

**Comment by quasiben** [comment]
Thanks @cjnolet for the confirmation

**Pull request merged**
