### PR TITLE
[NO MRG] Add blank line to trigger CI

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
Seeing the following test error on [CI]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-gpu-build/detail/ucx-py-gpu-build/1560/pipeline/ ). Any ideas why this is coming up?

```
tests/test_guarantee_msg_order.py::test_mismatch ERROR Ignored except: <class 'ValueError'> Both peers must set guarantee_msg_order identically
ERROR Ignored except: <class 'ValueError'> Both peers must set guarantee_msg_order identically
```

**Comment by pentschev** [comment]
This is one of the errors I've been seeing lately with IB testing, but obviously not only related to that. Is it failing consistently or non-deterministically? Also, were you able to reproduce that on a DGX?

**Comment by pentschev** [comment]
I ran that test 100 times on a DGX-1 and couldn't get it to fail.

**Comment by jakirkham** [comment]
I'm only seeing it on CI. I've only tried maybe 3 times on CI. That said, it has errored all 3 times. So most likely deterministic.

**Comment by jakirkham** [comment]
Looking a bit more closely, it seems we are checking for a `ValueError` to be raised in this test [here]( https://github.com/rapidsai/ucx-py/blob/c5583fb31037d135dad316db4e62773eb9776eb1/tests/test_guarantee_msg_order.py#L11-L14 ) and [here]( https://github.com/rapidsai/ucx-py/blob/c5583fb31037d135dad316db4e62773eb9776eb1/tests/test_guarantee_msg_order.py#L17-L20 ). This expected `ValueError` should be [raised in `exchange_peer_info`]( https://github.com/rapidsai/ucx-py/blob/527cc99e86c359ca53260da580f44575c436cc3b/ucp/_libs/core.pyx#L65-L66 ). However that doesn't appear to be happening. @madsbk, do you know why that might be?

**Comment by madsbk** [comment]
> Looking a bit more closely, it seems we are checking for a `ValueError` to be raised in this test [here](https://github.com/rapidsai/ucx-py/blob/c5583fb31037d135dad316db4e62773eb9776eb1/tests/test_guarantee_msg_order.py#L11-L14) and [here](https://github.com/rapidsai/ucx-py/blob/c5583fb31037d135dad316db4e62773eb9776eb1/tests/test_guarantee_msg_order.py#L17-L20). This expected `ValueError` should be [raised in `exchange_peer_info`](https://github.com/rapidsai/ucx-py/blob/527cc99e86c359ca53260da580f44575c436cc3b/ucp/_libs/core.pyx#L65-L66). However that doesn't appear to be happening. @madsbk, do you know why that might be?

The `ERROR Ignored except: <class 'ValueError'> Both peers must set guarantee_msg_order identically` message is a red herring. it happens because  `with pytest.raises` only catches the _client side_ and not the _server side_, which also raises the error.

**Comment by madsbk** [comment]
rerun tests

**Comment by jakirkham** [comment]
Do we know why only one `ValueError` is caught? Is this expected or is it some sort intermittent failure?

**Pull request closed without merging**
