### PR TITLE
Drops outdated build flags from `build_ext`

### PR DESCRIPTION
**Pull request by jakirkham**
Merges https://github.com/rapidsai/ucx-py/pull/260
Merges https://github.com/rapidsai/ucx-py/pull/261
Fixes https://github.com/rapidsai/ucx-py/issues/258
Fixes https://github.com/rapidsai/ucx-py/issues/259

Consolidates the changes to remove `--with-prof` and `--with-cuda` flags from the custom `build_ext`. Also goes ahead and removes the custom `build_ext` class entirely. After all it doesn't appear to have a use after removing both of these.

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by quasiben** [comment]
What do you think about consolidating all the setup.py/Makefile PRs into this PR ?

**Comment by jakirkham** [comment]
That was sort of the idea. Though I think I'll skip removing the `Makefile` here as that needs more work.

**Comment by jakirkham** [comment]
Anyways should be good to go (if it looks ok to you) 🙂

**Comment by jakirkham** [comment]
Thanks :)

**Pull request merged**
