### PR TITLE
Add multi-GPU debug test

### PR DESCRIPTION
**Pull request by pentschev**
Adds a more complex pytest based on the work from https://github.com/rapidsai/ucx-py/pull/482 . This test is not perfect and fails in some cases, which shows how important it is for us to test this sort of scenario in a more frequent basis. One example of problems that can be reproduced with this is running the `cudf.series` test with InfiniBand, resulting in the following crash:

```
lx5: dgx13: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000002 00000000 00000000 00000000
00000000 93003204 10003878 0002ded2
[dgx13:46740:0:46740] rc_verbs_iface.c:65   send completion with error: local protection error qpn 0x3878 wrid 0x1 vendor_err 0x32
==== backtrace (tid:  46740) ====
 0  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/libucs.so.0(ucs_handle_error+0x12d) [0x7f8e15a7047d]
 1  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/libucs.so.0(ucs_fatal_error_message+0x51) [0x7f8e15a6d291]
 2  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/libucs.so.0(+0x241c7) [0x7f8e15a711c7]
 3  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/libucs.so.0(ucs_log_dispatch+0xd9) [0x7f8e15a712f9]
 4  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/ucx/libuct_ib.so.0(+0x1d07e) [0x7f8e10c2507e]
 5  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/ucx/libuct_ib.so.0(+0x1d6be) [0x7f8e10c256be]
 6  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/libucp.so.0(ucp_worker_progress+0x6a) [0x7f8e15b1109a]
 7  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/lib/python3.7/site-packages/ucp/_libs/ucx_api.cpython-37m-x86_64-linux-gnu.so(+0x15211) [0x7f8e15b8b211]
 8  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyMethodDef_RawFastCallDict+0x20a) [0x55b67ba895da]
 9  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(+0x16c0c1) [0x55b67babf0c1]
10  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(PyObject_Call+0x6e) [0x55b67ba7a75e]
11  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x1f6a) [0x55b67bb21d6a]
12  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalCodeWithName+0xab8) [0x55b67ba690b8]
13  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0x387) [0x55b67bab79e7]
14  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x6a0) [0x55b67bb204a0]
15  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallDict+0x10b) [0x55b67ba6996b]
16  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyObject_Call_Prepend+0x63) [0x55b67ba87e03]
17  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyObject_FastCallKeywords+0x49b) [0x55b67babf57b]
18  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(+0x201263) [0x55b67bb54263]
19  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyMethodDef_RawFastCallDict+0x194) [0x55b67ba89564]
20  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyCFunction_FastCallDict+0x21) [0x55b67ba897a1]
21  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x5da3) [0x55b67bb25ba3]
22  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55b67bab775b]
23  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x6a0) [0x55b67bb204a0]
24  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55b67bab775b]
25  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x6a0) [0x55b67bb204a0]
26  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55b67bab775b]
27  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x6a0) [0x55b67bb204a0]
28  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55b67bab775b]
29  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x6a0) [0x55b67bb204a0]
30  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalCodeWithName+0xab8) [0x55b67ba690b8]
31  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallDict+0x1d5) [0x55b67ba69a35]
32  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x1f6a) [0x55b67bb21d6a]
33  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55b67bab775b]
34  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x6a0) [0x55b67bb204a0]
35  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55b67bab775b]
36  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x6a0) [0x55b67bb204a0]
37  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55b67bab775b]
38  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x416) [0x55b67bb20216]
39  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalCodeWithName+0x2f9) [0x55b67ba688f9]
40  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyFunction_FastCallKeywords+0x387) [0x55b67bab79e7]
41  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalFrameDefault+0x14e7) [0x55b67bb212e7]
42  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_PyEval_EvalCodeWithName+0x2f9) [0x55b67ba688f9]
43  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(PyEval_EvalCodeEx+0x44) [0x55b67ba69824]
44  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(PyEval_EvalCode+0x1c) [0x55b67ba6984c]
45  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(+0x22c684) [0x55b67bb7f684]
46  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(PyRun_StringFlags+0x7d) [0x55b67bb8a9dd]
47  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(PyRun_SimpleStringFlags+0x3f) [0x55b67bb8aa3f]
48  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(+0x237b3d) [0x55b67bb8ab3d]
49  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(_Py_UnixMain+0x3c) [0x55b67bb8aebc]
50  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f8e8c4e5b97]
51  /datasets/pentschev/miniconda3/envs/rn-102-0.14.0b200518/bin/python(+0x1dcbd0) [0x55b67bb2fbd0]
=================================
```

Running the same test with TCP over UCX only will succeed.

Another issue is running with NVLink, causing the test to always hang -- but this is also reproducible with https://github.com/rapidsai/ucx-py/blob/branch-0.14/tests/test_send_recv_two_workers.py .

### CODE REVIEW

**Comment by quasiben** [comment]
Thank you for doing this @pentschev .   A few questions

When you saw the bug was this with both IB/NVLink enabled ?  
Were you enabling hardware with UCX_TLS ?  Should we add these as CLI options ?
Is the bug related to https://github.com/openucx/ucx/issues/3564 ?

**Comment by pentschev** [comment]
> When you saw the bug was this with both IB/NVLink enabled ?

IB only.

> Were you enabling hardware with UCX_TLS ? Should we add these as CLI options ?

Yes, using `UCX_TLS`. I purposely didn't add any more controls as this would limit the reach of that test, since it's currently meant as a debug test. The way it is written now allows users to control all UCX details from environment variables, the exception being IB interfaces as I don't see any simple way of working around that without a lot of manual configuration per-GPU/IB device.

> Is the bug related to openucx/ucx#3564 ?

The error is similar, I currently have no way of knowing if it's related to that.

**Comment by pentschev** [comment]
I don't want to make this PR a discussion of the bug that will likely be lost/difficult to find, therefore I filed an issue for that in: https://github.com/rapidsai/ucx-py/issues/531#issue-622520435 .

**Comment by quasiben** [comment]
> I don't want to make this PR a discussion of the bug that will likely be lost/difficult to find, therefore I filed an issue for that in: #531 (comment) 

Thank you.   I'll merge this in.  Thank you again!

**Comment by quasiben** [comment]
@rapidsai/admins can you merge this in ?  There is a small change to the CI test as part of this PR

**Comment by quasiben** [comment]
Thanks @raydouglass

**Pull request merged**
