### PR TITLE
Ensure rkey is destroyed when flush callback isn't called

### PR DESCRIPTION
**Pull request by pentschev**
Resolve UCX warnings such as:

```
[1636059854.502867] [1a7f04145417:10924:0]           mpool.c:44   UCX WARN  object 0x5556f078ab40 was not returned to mpool ucp_rkeys
[1636059854.501943] [1a7f04145417:10998:0]           mpool.c:44   UCX WARN  object 0x55bafa4cdc40 was not returned to mpool ucp_rkeys
```

Downgrade UCX-Py assertion errors to debug logs:

```
Traceback (most recent call last):
  File "/workspace/ucp/exceptions.py", line 13, in log_errors
    yield
  File "ucp/_libs/transfer_common.pyx", line 55, in ucp._libs.ucx_api._send_callback
    cb_func(req, exception, *cb_args, **cb_kwargs)
  File "ucp/_libs/ucx_rkey.pyx", line 13, in ucp._libs.ucx_api._ucx_remote_mem_finalizer_post_flush
    assert exception is None
AssertionError
```

### CODE REVIEW

**Comment by pentschev** [comment]
@MattBBaker FYI, since you're the original author.

**Comment by MattBBaker** [comment]
Okay, I've seen that on occasion and long wondered about the source, this makes sense. 👍

**Review by dmitrygx — APPROVED** [review]

**Comment by pentschev** [comment]
rerun tests

**Review by madsbk — APPROVED** [review]
LGTM

**Comment by pentschev** [comment]
Thanks @MattBBaker @dmitrygx and @madsbk for the reviews!

**Pull request merged**
