### PR TITLE
fea/add-ucx-listener-test

### PR DESCRIPTION
**Pull request by quasiben**
PR adds tests with message passing scheme similar to dask.  Tests use both large and small cudf and cupy objects

### CODE REVIEW

**Comment by quasiben** [comment]
@mrocklin what do you think about the queueing system used in this test ?  My plan is to do something similar in dask

**Comment by mrocklin** [comment]
> what do you think about the queueing system used in this test ?

Why is it necessary?  In theory, it's somewhat unclean to create an unchecked buffer like this.  Ideally we only pull things off of UCX when we're ready for them so that UCX (or whatever transport it uses) feels some pressure if one end starts sending things too quickly.  I don't know that this will affect us much in the common case, but it's sort of general practice not to do these things if you can avoid it.

So, why are we doing this?  What are we working around?

**Comment by quasiben** [comment]
The issue in UCX seems to be that when await write/read with large messages the [Rendezvous-Protocol](https://github.com/openucx/ucx/wiki/Rendezvous-Protocol) is invoked and this can create a deadlock.   One solution to this problem is to move the read inside (make current read a `_read` function) the coroutine `serve_forever` and post the reads to a queue to be consumed by a public facing `read` function

**Comment by quasiben** [comment]
Another solution to the problem is not calling `await write` but I don't fully understand why this works.  @Akshay-Venkatesh can you explain again (apologies) 

I didn't explore this very much as much of distributed relies on `await write/await read`

**Comment by mrocklin** [comment]
> The issue in UCX seems to be that when await write/read with large messages the Rendezvous-Protocol is invoked and this can create a deadlock.

After reading through these comments and that document I still don't understand why UCX would deadlock here.

**Comment by Akshay-Venkatesh** [comment]
> > The issue in UCX seems to be that when await write/read with large messages the Rendezvous-Protocol is invoked and this can create a deadlock.
> 
> After reading through these comments and that document I still don't understand why UCX would deadlock here.

https://github.com/rapidsai/ucx-py/issues/140#issuecomment-519596036

**Comment by mrocklin** [comment]
Is it ok to close this?

**Comment by quasiben** [comment]
No, i would like to keep this as a valid test -- I'll finish it up now

**Comment by quasiben** [comment]
merging now

**Pull request merged**
