### PR TITLE
Fix doc style

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes [a linting error]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-style/detail/ucx-py-style/808/pipeline/ ) observed in PR ( https://github.com/rapidsai/ucx-py/pull/574 ).

### CODE REVIEW

**Comment by jakirkham** [comment]
Seeing the test failure from Distributed below (and some variants of it) on [CI]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-gpu-build/detail/ucx-py-gpu-build/2251/pipeline ). This is a consequence of the change in PR ( https://github.com/rapidsai/rmm/pull/477 ), which causes RMM's `DeviceBuffer` to have `strides` as `None` in the `header` when serialized. Simply always setting RMM's `DeviceBuffer`'s `strides` in the `header` as is done in PR ( https://github.com/dask/distributed/pull/4039 ) should fix the issue.

<details>

```python
_______________________ test_serialize_numba_from_rmm[0] _______________________

size = 0

    @pytest.mark.parametrize("size", [0, 3, 10])
    def test_serialize_numba_from_rmm(size):
        np = pytest.importorskip("numpy")
        rmm = pytest.importorskip("rmm")
    
        if not cuda.is_available():
            pytest.skip("CUDA is not available")
    
        x_np = np.arange(size, dtype="u1")
    
        x_np_desc = x_np.__array_interface__
        (x_np_ptr, _) = x_np_desc["data"]
        (x_np_size,) = x_np_desc["shape"]
        x = rmm.DeviceBuffer(ptr=x_np_ptr, size=x_np_size)
    
        header, frames = serialize(x, serializers=("cuda", "dask", "pickle"))
        header["type-serialized"] = pickle.dumps(cuda.devicearray.DeviceNDArray)
    
>       y = deserialize(header, frames, deserializers=("cuda", "dask", "pickle", "error"))

/opt/conda/envs/gdf/lib/python3.7/site-packages/distributed/protocol/tests/test_numba.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/serialize.py:335: in deserialize
    return loads(header, frames)
/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/cuda.py:28: in cuda_loads
    return loads(header, frames)
/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/numba.py:46: in cuda_deserialize_numba_ndarray
    gpu_data=numba.cuda.as_cuda_array(frame).gpu_data,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7fc3376ace50>
shape = (0,), strides = None, dtype = dtype('uint8'), stream = 0
writeback = None
gpu_data = <numba.cuda.cudadrv.driver.MemoryPointer object at 0x7fc3376acd90>

    def __init__(self, shape, strides, dtype, stream=0, writeback=None,
                 gpu_data=None):
        """
        Args
        ----
    
        shape
            array shape.
        strides
            array strides.
        dtype
            data type as np.dtype coercible object.
        stream
            cuda stream.
        writeback
            Deprecated.
        gpu_data
            user provided device memory for the ndarray data buffer
        """
        if isinstance(shape, int):
            shape = (shape,)
        if isinstance(strides, int):
            strides = (strides,)
        dtype = np.dtype(dtype)
        self.ndim = len(shape)
>       if len(strides) != self.ndim:
E       TypeError: object of type 'NoneType' has no len()

/opt/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py:90: TypeError
```

</details>

**Comment by jakirkham** [comment]
Interestingly CuPy does not run into this error, this appears to be due to the fact that it will just interpret `strides is None` as C-contiguous (similar to CuPy). This seems like desirable behavior to have in Numba as well. Submitted PR ( https://github.com/numba/numba/pull/6122 ) to make that change in Numba.

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Why is that? We still have `version` defined. It's just extracted from `release` instead.

**Comment by raydouglass** [comment]
That script is run when a branch and release is cut. So your change in this PR will be reverted again when branch-0.17 is created unless you update the script to no longer overwrite the value.

**Comment by jakirkham** [comment]
Yep, that makes sense. Thanks for the explanation, Ray! 😄

Does this look right?

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Looks like this new CI failure is wasn't able to reproduce the change locally until upgrading `rmm`. My guess is it relates to PR ( https://github.com/rapidsai/rmm/pull/466 ). What I'm less sure about is whether other things to be rebuilt (like `cudf`) to include that change.

**Comment by jakirkham** [comment]
Am also able to reproduce this with the array benchmark. Just need to configure it to use RMM like so (on CI we use `-o cupy` instead of `-o rmm`). This means it is just an issue with RMM and UCX (not cuDF).

```
python benchmarks/local-send-recv.py -o rmm --server-dev 0 --client-dev 0 --reuse-alloc
```

<details>

```python
Server Running at 10.33.225.165:45633
Client connecting to server at 10.33.225.165:45633
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/datasets/jkirkham/devel/ucx-py/benchmarks/local-send-recv.py", line 147, in client
    loop.run_until_complete(run())
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/datasets/jkirkham/devel/ucx-py/benchmarks/local-send-recv.py", line 126, in run
    t1 = np.arange(args.n_bytes, dtype="u1")
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/cupy/creation/ranges.py", line 55, in arange
    ret = cupy.empty((size,), dtype=dtype)
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/cupy/creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 544, in cupy.cuda.memory.alloc
  File "/datasets/jkirkham/miniconda/envs/rapids15dev/lib/python3.8/site-packages/rmm/rmm.py", line 270, in rmm_cupy_allocator
    buf = librmm.device_buffer.DeviceBuffer(size=nbytes)
  File "rmm/_lib/device_buffer.pyx", line 70, in rmm._lib.device_buffer.DeviceBuffer.__cinit__
MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp68: cudaErrorMemoryAllocation out of memory
```

</details>

**Comment by jakirkham** [comment]
Trying to address these issues in PR ( https://github.com/rapidsai/ucx-py/pull/577 ) in combination with upstream changes to RMM ( https://github.com/rapidsai/rmm/pull/490 ).

**Comment by jakirkham** [comment]
rerun tests

Trying to pickup the new nightlies from PR ( https://github.com/rapidsai/rmm/pull/493 ).

**Comment by jakirkham** [comment]
Looks like we are still seeing this issue with the new RMM package.

**Comment by jakirkham** [comment]
Am beginning to think we are just choosing a problematic default for pool size.

**Comment by jakirkham** [comment]
rerun tests

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Pull request merged**
