### PR TITLE
Update to UCX 1.8.0

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by pentschev** [comment]
I don't expect any issues, but it would be nice to wait until @beckernick and @VibhuJawa can test some large workflows just to be on the safe side.

**Comment by quasiben** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by quasiben** [comment]
Last rerun got things going again.  Should we merge in ?

**Comment by jakirkham** [comment]
Sounds good to me. Though we need a review from OPS.

**Comment by quasiben** [comment]
Thanks @raydouglass

**Pull request merged**
