### PR TITLE
Some cleanup of topological distance

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a `.pxd` file for `topological_distance`. Types methods arguments and variables in methods. Drops some casts where the type was unchanged.

### CODE REVIEW

**Comment by pentschev** [comment]
LGTM, but TBH, I'm still ignorant of most of how Cython code should be structured. Could you clarify what is this solving/improving?

**Comment by jakirkham** [comment]
Most of the performance that one gets out of Cython relies on correctly typing variables as tightly as possible as early as possible. This avoids needing to work with Python objects, which require a fair bit of extra handling. Thus allowing Cython to make better choices about what to do with these variables.

**Comment by pentschev** [comment]
Got it, thanks @jakirkham for clarifying! 😄

**Comment by jakirkham** [comment]
Of course. Thanks for the review! 😄

**Pull request merged**
