### PR TITLE
Test Distributed Nannies

### PR DESCRIPTION
**Pull request by quasiben**
PR adds a test for nanny closure from Distributed
xref https://github.com/dask/distributed/pull/3747

@rapidsai/admins can you review and merge ?

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

(appears CI is not running here?)

**Comment by pentschev** [comment]
> (appears CI is not running here?)

The tests passed, are you seeing any other issues?

**Comment by jakirkham** [comment]
Seems fine. Just CI wasn’t running previously. If it has run since, great!

**Comment by pentschev** [comment]
> Seems fine. Just CI wasn’t running previously. If it has run since, great!

Cool, thanks for confirmation. Merging.

**Pull request merged**
