### PR TITLE
Clean Benchmarks

### PR DESCRIPTION
**Pull request by quasiben**
This PR moves the non-working/older benchmarks into a separate directory .  I haven't looked in detail at all the benchmarks but though we should keep them around for a little bit longer.  Perhaps as we start benchmarking in earnest we can remove both `old_test` and `old_benchmarks`

Thoughts ?

### CODE REVIEW

**Comment by pentschev** [comment]
Sounds good to me. If we think they may not be too useful in the future, we could just create a new branch or a tag to find them if needed and delete them from the main branch.

**Comment by quasiben** [comment]
@jakirkham when you have a minute can you review ?

**Comment by jakirkham** [comment]
Yeah I agree with Peter. Why not just delete them if they are not relevant? We can always recover them with Git if we were wrong. 🙂

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks Ben! 😄

**Pull request merged**
