### PR TITLE
Add CPU affinity argument to tests and cleanup debug-tests

### PR DESCRIPTION
**Pull request by pentschev**

### CODE REVIEW

**Comment by quasiben** [comment]
Looks great!   Tested with the new CPU affinity as well:

```
UCX_TLS=tcp,sockcm UCX_SOCKADDR_TLS_PRIORITY=sockcm python local-send-recv.py --server-dev 0 --client-dev 5 --object_type numpy --reuse-alloc --n-bytes 1GB --client-only --server-address 10.33.228.80 --port 33436 --n-iter 5 --server-cpu-affinity 2
Server Running at 10.33.228.80:33436
Client connecting to server at 10.33.228.80:33436
Roundtrip benchmark
--------------------------
n_iter      | 5
n_bytes     | 1000.00 MB
object      | numpy
reuse alloc | True
==========================
Device(s)    | Single CPU
Average     | 1.83 GB/s
--------------------------
Iterations
--------------------------
000         |  1.48 GB/s
001         |  2.09 GB/s
002         |  1.86 GB/s
003         |  1.90 GB/s
004         |  1.95 GB/s
```

Do you think we should list the affinity in the output ?

**Comment by pentschev** [comment]
@quasiben yes, that makes sense, added it in the latest commit.

**Comment by quasiben** [comment]
We are getting conda resolution issues:

```


UnsatisfiableError: The following specifications were found

to be incompatible with the existing python installation in your environment:



Specifications:



  - arrow-cpp=0.15.0 -> python[version='>=3.8,<3.9.0a0']

  - pyarrow=0.15.0 -> python[version='2.7.*|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.6.*|3.5.*|3.4.*']



Your python: python=3.7
```

**Comment by jakirkham** [comment]
Are we picking up the latest `cudf` version?

**Comment by pentschev** [comment]
I don't know what we're picking, this PR isn't changing anything w.r.t. packaging, so it probably is something with conda packages or CI?

**Comment by quasiben** [comment]
In the CI I see:
> Examining dask-cudf=0.15

```
Solving environment: ...working... 
Building graph of deps:   0%|          | 0/12 [00:00<?, ?it/s]
Examining cudf=0.15:   0%|          | 0/12 [00:00<?, ?it/s]   
Examining dask[version='>=2.8.1']:   8%|▊         | 1/12 [00:31<05:47, 31.61s/it]
Examining dask[version='>=2.8.1']:  17%|█▋        | 2/12 [00:31<02:38, 15.81s/it]
Examining dask-cudf=0.15:  17%|█▋        | 2/12 [00:40<02:38, 15.81s/it]         
Examining dask-cudf=0.15:  25%|██▌       | 3/12 [00:40<02:02, 13.63s/it]
Examining cudatoolkit=10.0:  25%|██▌       | 3/12 [00:45<02:02, 13.63s/it]
Examining cudatoolkit=10.0:  33%|███▎      | 4/12 [00:45<01:28, 11.09s/it]
Examining numpy[version='>=1.16']:  33%|███▎      | 4/12 [00:45<01:28, 11.09s/it]
Examining distributed[version='>=2.8.1']:  42%|████▏     | 5/12 [00:49<01:17, 11.09s/it]
Examining distributed[version='>=2.8.1']:  50%|█████     | 6/12 [00:49<00:50,  8.42s/it]
Examining cupy[version='>=6.5.0']:  50%|█████     | 6/12 [00:57<00:50,  8.42s/it]       
Examining cupy[version='>=6.5.0']:  58%|█████▊    | 7/12 [00:57<00:41,  8.28s/it]
Examining pyarrow=0.15.0:  58%|█████▊    | 7/12 [01:45<00:41,  8.28s/it]         
Examining pyarrow=0.15.0:  67%|██████▋   | 8/12 [01:45<01:20, 20.12s/it]
Examining @/linux-64::__glibc==2.17=0:  67%|██████▋   | 8/12 [01:46<01:20, 20.12s/it]
Examining @/linux-64::__glibc==2.17=0:  75%|███████▌  | 9/12 [01:46<00:43, 14.53s/it]
Examining @/linux-64::__cuda==10.2=0:  75%|███████▌  | 9/12 [01:46<00:43, 14.53s/it] 
Examining python=3.7:  83%|████████▎ | 10/12 [01:46<00:29, 14.53s/it]               
Examining arrow-cpp=0.15.0:  92%|█████████▏| 11/12 [01:48<00:14, 14.53s/it]
Examining arrow-cpp=0.15.0: 100%|██████████| 12/12 [01:48<00:00, 10.28s/it]
                                                                           

Determining conflicts:   0%|          | 0/12 [00:00<?, ?it/s]
Examining conflict for dask-cudf cudf:   0%|          | 0/12 [00:00<?, ?it/s]
Examining conflict for cudf dask pyarrow numpy cupy arrow-cpp:   8%|▊         | 1/12 [00:00<00:02,  4.15it/s]
Examining conflict for cudf dask pyarrow numpy cupy arrow-cpp:  17%|█▋        | 2/12 [00:00<00:01,  8.29it/s]
Examining conflict for arrow-cpp pyarrow cudf:  17%|█▋        | 2/12 [00:16<00:01,  8.29it/s]                
Examining conflict for arrow-cpp pyarrow cudf:  25%|██▌       | 3/12 [00:16<00:45,  5.00s/it]
Examining conflict for dask pyarrow cudf:  25%|██▌       | 3/12 [00:17<00:45,  5.00s/it]     
Examining conflict for dask pyarrow cudf:  33%|███▎      | 4/12 [00:17<00:29,  3.63s/it]
Examining conflict for cudf dask dask-cudf pyarrow numpy distributed cupy python arrow-cpp:  33%|███▎      | 4/12 [00:20<00:29,  3.63s/it]
Examining conflict for cudf dask dask-cudf pyarrow numpy distributed cupy python arrow-cpp:  42%|████▏     | 5/12 [00:20<00:24,  3.51s/it]
Examining conflict for dask dask-cudf pyarrow cudf:  42%|████▏     | 5/12 [00:23<00:24,  3.51s/it]                                        
Examining conflict for dask dask-cudf pyarrow cudf:  50%|█████     | 6/12 [00:23<00:20,  3.47s/it]
Examining conflict for cudf dask dask-cudf pyarrow numpy cupy arrow-cpp:  50%|█████     | 6/12 [00:25<00:20,  3.47s/it]
Examining conflict for cudf dask dask-cudf pyarrow numpy cupy arrow-cpp:  58%|█████▊    | 7/12 [00:25<00:15,  3.09s/it]
Examining conflict for cupy cudatoolkit pyarrow cudf:  58%|█████▊    | 7/12 [00:27<00:15,  3.09s/it]                   
Examining conflict for cupy cudatoolkit pyarrow cudf:  67%|██████▋   | 8/12 [00:27<00:10,  2.59s/it]
Examining conflict for cupy dask cudf numpy:  67%|██████▋   | 8/12 [00:28<00:10,  2.59s/it]         
Examining conflict for cupy dask cudf numpy:  75%|███████▌  | 9/12 [00:28<00:06,  2.18s/it]
Examining conflict for cudf dask dask-cudf pyarrow numpy distributed cupy arrow-cpp:  75%|███████▌  | 9/12 [00:31<00:06,  2.18s/it]
Examining conflict for cudf dask dask-cudf pyarrow numpy distributed cupy arrow-cpp:  83%|████████▎ | 10/12 [00:31<00:05,  2.57s/it]
Examining conflict for dask dask-cudf cudf:  83%|████████▎ | 10/12 [00:37<00:05,  2.57s/it]                                         
Examining conflict for dask dask-cudf cudf:  92%|█████████▏| 11/12 [00:37<00:03,  3.47s/it]
Examining conflict for cupy dask-cudf cudf:  92%|█████████▏| 11/12 [00:37<00:03,  3.47s/it]
Examining conflict for cupy dask-cudf cudf: 100%|██████████| 12/12 [00:37<00:00,  2.47s/it]
Examining conflict for cupy cudf: 100%|██████████| 12/12 [00:37<00:00,  2.47s/it]          
Examining conflict for cupy cudf: : 13it [00:37,  1.77s/it]                      
Examining conflict for pyarrow cudf: : 13it [00:38,  1.77s/it]
Examining conflict for pyarrow cudf: : 14it [00:38,  1.56s/it]
Examining conflict for cudf dask dask-cudf distributed cupy python: : 14it [00:40,  1.56s/it]
Examining conflict for cudf dask dask-cudf distributed cupy python: : 15it [00:40,  1.43s/it]
Examining conflict for cudf dask pyarrow numpy cupy: : 15it [00:42,  1.43s/it]               
Examining conflict for cudf dask pyarrow numpy cupy: : 16it [00:42,  1.64s/it]
Examining conflict for dask-cudf pyarrow cudf: : 16it [00:44,  1.64s/it]      
Examining conflict for dask-cudf pyarrow cudf: : 17it [00:44,  1.97s/it]
Examining conflict for dask dask-cudf: : 17it [00:45,  1.97s/it]        
Examining conflict for dask dask-cudf: : 18it [00:45,  1.43s/it]
Examining conflict for dask dask-cudf distributed: : 18it [00:45,  1.43s/it]
Examining conflict for dask pyarrow numpy distributed cupy python arrow-cpp: : 19it [00:46,  1.43s/it]
Examining conflict for dask pyarrow numpy distributed cupy python arrow-cpp: : 20it [00:46,  1.15s/it]
Examining conflict for dask pyarrow distributed: : 20it [00:49,  1.15s/it]                            
Examining conflict for dask pyarrow distributed: : 21it [00:49,  1.82s/it]
Examining conflict for cupy numpy: : 21it [00:50,  1.82s/it]              
Examining conflict for cupy numpy: : 22it [00:50,  1.64s/it]
Examining conflict for pyarrow numpy cupy python arrow-cpp: : 22it [00:53,  1.64s/it]
Examining conflict for pyarrow numpy cupy python arrow-cpp: : 23it [00:53,  1.88s/it]
Examining conflict for cupy distributed: : 23it [00:55,  1.88s/it]                   
Examining conflict for cupy distributed: : 24it [00:55,  2.16s/it]
Examining conflict for arrow-cpp pyarrow: : 24it [00:56,  2.16s/it]
Examining conflict for arrow-cpp pyarrow: : 25it [00:56,  1.82s/it]
Examining conflict for __cuda: : 25it [00:58,  1.82s/it]           
Examining conflict for __cuda: : 26it [00:58,  1.65s/it]
                                                        

Found conflicts! Looking for incompatible packages.

This can take several minutes.  Press CTRL-C to abort.

failed
```

**Comment by quasiben** [comment]
I suspect we need a new version of arrow ?  In dask-cuda ops folks merged in https://github.com/rapidsai/dask-cuda/pull/317 which takes care of upgrades now.  I am seeing arrow 0.17 as the new version listed here:
https://github.com/rapidsai/integration/blob/58e8b8f07acc79eb9b70a8834e1ffbd29f4bafb5/conda/recipes/nightly-versions.yaml

@raydouglass do you have thoughts here ?

**Comment by raydouglass** [comment]
cudf depends on 0.17.1 for arrow (https://github.com/rapidsai/cudf/blob/branch-0.15/conda/recipes/cudf/meta.yaml#L36). You have an explicit install of 0.15 here: https://github.com/rapidsai/ucx-py/blob/branch-0.15/ci/gpu/build.sh#L52

I think you can just update them and be good to go.

**Comment by pentschev** [comment]
I don't think we need an explicit dependency to arrow versions, I removed both packages to see if that works.

Thanks for checking that @raydouglass !

**Pull request merged**
