### PR TITLE
Fix several tests for UCX 1.10+ support

### PR DESCRIPTION
**Pull request by pentschev**
The effort to support 1.10+ is still ongoing, this PR is one part of it now fixing various of tests.

### CODE REVIEW

**Comment by pentschev** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by pentschev** [comment]
@madsbk @quasiben could one of you review this?

**Review by madsbk — APPROVED** [review]
LGTM

**Comment by pentschev** [comment]
Thanks @madsbk !

**Pull request merged**
