### PR TITLE
Add container NVLink section and lint file

### PR DESCRIPTION
**Pull request by jacobtomlinson**
I've added a section to the README about `NVLink and Docker/Kubernetes` to explain how to use NVLink when using containers to isolate/deploy processes.

I've also corrected markdown linting issues and spelling/grammar generally.

### CODE REVIEW

**Comment by quasiben** [comment]
This is really great!  Thank you for doing this @jacobtomlinson !  Would you mind adding this to the docs as well https://ucx-py.readthedocs.io/en/latest/ ?  If you're busy, no problem -- we can take care of this later

**Comment by jacobtomlinson** [comment]
Happy to! Do you think it should be there instead or as well as?

**Comment by quasiben** [comment]
I would say instead -- over time we might want to reduce the README in favor of the docs

**Comment by quasiben** [comment]
Thanks @jacobtomlinson

**Pull request merged**
