### PR TITLE
Cleanup tests

### PR DESCRIPTION
**Pull request by mrocklin**
I'm slowly walking through tests as a way to get into the library.  A couple changes here, I'll probably add more in a bit.

### CODE REVIEW

**Comment by mrocklin** [comment]
In https://github.com/Akshay-Venkatesh/ucx-py/pull/86/commits/6799b6cfd4da034ca58d83c3da7af9a37bbdb1c8 I start to convert over a couple of the simpler scripts in `tests/` to pytest style test functions.  The sense I get is that this will make sense for some of these scripts, which operate as tests, but not so much for some other scripts, which operate more as benchmarks.  

Would you agree @Akshay-Venkatesh ?

**Comment by Akshay-Venkatesh** [comment]
@mrocklin agreed!

**Comment by mrocklin** [comment]
Running tests individually is usually fine, however I'm running into troubles when I run them all in the same process.  Here is one example

```
(ucx-dev) mrocklin@dgx15:~/ucx-py$ py.test tests/ --verbose -s
======================================================= test session starts ========================================================
platform linux -- Python 3.7.3, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python
cachedir: .pytest_cache
rootdir: /home/nfs/mrocklin/ucx-py
plugins: asyncio-0.10.0
collected 33 items

tests/test_buffer_region.py::test_set_read PASSED
tests/test_buffer_region.py::test_numpy[True-u1] PASSED
tests/test_buffer_region.py::test_numpy[True-u8] PASSED
tests/test_buffer_region.py::test_numpy[True-i1] PASSED
tests/test_buffer_region.py::test_numpy[True-i8] PASSED
tests/test_buffer_region.py::test_numpy[True-f4] PASSED
tests/test_buffer_region.py::test_numpy[True-f8] PASSED
tests/test_buffer_region.py::test_numpy[False-u1] PASSED
tests/test_buffer_region.py::test_numpy[False-u8] PASSED
tests/test_buffer_region.py::test_numpy[False-i1] PASSED
tests/test_buffer_region.py::test_numpy[False-i8] PASSED
tests/test_buffer_region.py::test_numpy[False-f4] PASSED
tests/test_buffer_region.py::test_numpy[False-f8] PASSED
tests/test_buffer_region.py::test_cupy[u1] PASSED
tests/test_buffer_region.py::test_cupy[u8] PASSED
tests/test_buffer_region.py::test_cupy[i1] PASSED
tests/test_buffer_region.py::test_cupy[i8] PASSED
tests/test_buffer_region.py::test_cupy[f4] PASSED
tests/test_buffer_region.py::test_cupy[f8] PASSED
tests/test_dask_gpu_scatter.py::test_dask_gpu_scatter SKIPPED
tests/test_default_address.py::test_get_address PASSED
tests/test_multiple_listeners.py::test_multiple_listeners PASSED
tests/test_no_cuda.py::test_alloc_cuda_raises SKIPPED
tests/test_no_cuda.py::test_free_cuda_raises SKIPPED
tests/test_no_cuda.py::test_set_cuda_dev_raises SKIPPED
tests/test_port.py::test_zero_port PASSED
tests/test_send_recv_obj.py::test_send_recv_bytes [dgx15:26383:0:26383] ucp_listener.c:199  UCX Assertion `!((&(worker)->mt_lock)->mt_type) || (((&(worker)->mt_lock)->mt_type == UCP_MT_TYPE_MUTEX) ? 0 : ucs_spin_is_owner(&((&(worker)->mt_lock)->lock.mt_spinlock), pthread_self())) || !({ int _ret; if ((&(worker)->async)->mode == UCS_ASYNC_MODE_THREAD) { _ret = 0; } else if ((&(worker)->async)->mode == UCS_ASYNC_MODE_SIGNAL) { _ret = (((&(worker)->async)->signal.block_count > 0) && ((&(worker)->async)->signal.tid == ucs_get_tid())); } else { _ret = (&(worker)->async)->poll_block; } _ret; })' failed
==== backtrace ====
    0  /home/nfs/mrocklin/miniconda/envs/ucx-dev/lib/libucs.so.0(ucs_fatal_error+0x107) [0x7f2e3ebabdd7]
    1  /home/nfs/mrocklin/miniconda/envs/ucx-dev/lib/libucp.so.0(ucp_listener_create+0x6a8) [0x7f2e3f2ad2a8]
    2  /home/nfs/mrocklin/ucx-py/ucp/_libs/ucp_py.cpython-37m-x86_64-linux-gnu.so(ucp_py_listen+0x102) [0x7f2e3f5bbac2]
    3  /home/nfs/mrocklin/ucx-py/ucp/_libs/ucp_py.cpython-37m-x86_64-linux-gnu.so(+0x2acb9) [0x7f2e3f538cb9]
    4  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyMethodDef_RawFastCallKeywords+0x305) [0x555af4490785]
    5  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyCFunction_FastCallKeywords+0x21) [0x555af4490801]
    6  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyEval_EvalFrameDefault+0x544e) [0x555af44ec87e]
    7  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(+0x171cc6) [0x555af4488cc6]
    8  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(+0x171ecb) [0x555af4488ecb]
    9  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyMethodDef_RawFastCallKeywords+0xe9) [0x555af4490569]
   10  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyCFunction_FastCallKeywords+0x21) [0x555af4490801]
   11  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyEval_EvalFrameDefault+0x4755) [0x555af44ebb85]
   12  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyFunction_FastCallDict+0x10b) [0x555af442e50b]
   13  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyObject_Call_Prepend+0x63) [0x555af4445c43]
   14  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyObject_FastCallDict+0x9f) [0x555af442e9cf]
   15  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyEval_EvalFrameDefault+0x21a6) [0x555af44e95d6]
   16  /home/nfs/mrocklin/miniconda/envs/ucx-dev/bin/python(_PyGen_Send+0x2a2) [0x555af4489672]
   17  /home/nfs/mrocklin/miniconda/envs/ucx-dev/lib/python3.7/lib-dynload/_asyncio.cpython-37m-x86_64-linux-gnu.so(+0xc18e) [0x7f2e3f7b618e]
```

**Comment by mrocklin** [comment]
I also had to skip `test_dask_sum`.  It was hanging on something (though this might be Dask related).

**Comment by quasiben** [comment]
closing as we now have new python binding merged in #180

**Pull request closed without merging**
