### PR TITLE
Install CuPy from conda-forge

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Looks like we are getting some kind of crash.

```
tests/test_custom_send_recv.py::test_send_recv_cudf[<lambda>6] Fatal Python error: Aborted

Current thread 0x00007f4878d64740 (most recent call first):
  File "/conda/envs/gdf/lib/python3.7/asyncio/events.py", line 88 in _run
  File "/conda/envs/gdf/lib/python3.7/asyncio/base_events.py", line 1775 in _run_once
  File "/conda/envs/gdf/lib/python3.7/asyncio/base_events.py", line 539 in run_forever
  File "/conda/envs/gdf/lib/python3.7/asyncio/base_events.py", line 571 in run_until_complete
  File "/conda/envs/gdf/lib/python3.7/site-packages/pytest_asyncio/plugin.py", line 158 in pytest_pyfunc_call
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/python.py", line 1423 in runtest
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/runner.py", line 125 in pytest_runtest_call
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/runner.py", line 201 in <lambda>
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/runner.py", line 229 in from_call
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/runner.py", line 201 in call_runtest_hook
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/runner.py", line 176 in call_and_report
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/runner.py", line 95 in runtestprotocol
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/runner.py", line 80 in pytest_runtest_protocol
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/main.py", line 258 in pytest_runtestloop
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/main.py", line 237 in _main
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/main.py", line 193 in wrap_session
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/main.py", line 230 in pytest_cmdline_main
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
  File "/conda/envs/gdf/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/conda/envs/gdf/lib/python3.7/site-packages/_pytest/config/__init__.py", line 90 in main
  File "/conda/envs/gdf/bin/py.test", line 11 in <module>
ci/gpu/build.sh: line 130: 21446 Aborted                 (core dumped) UCXPY_IFNAME=eth0 UCX_MEMTYPE_CACHE=n UCX_TLS=tcp,cuda_copy,sockcm UCX_SOCKADDR_TLS_PRIORITY=sockcm py.test --cache-clear --junitxml=${WORKSPACE}/junit-ucx-py.xml -v --cov-config=.coveragerc --cov=cudf --cov-report=xml:${WORKSPACE}/ucp-coverage.xml --cov-report term tests/
```

**Comment by jakirkham** [comment]
@quasiben, have you seen this crash before?

**Comment by quasiben** [comment]
I have not seen that crash before.  I'll look into it now

**Comment by jakirkham** [comment]
Thanks Ben! 😀

**Pull request merged**
