### PR TITLE
Buffed send and receive

### PR DESCRIPTION
**Pull request by madsbk**
This PR make send and receive use a temporary buffer when communicating GPU memory and `UCXPY_COMM_BUFFER=y` is defined. 
Each buffer is associated a single endpoint thus all communication can use the same UCX memory registration. 

**Warning**, for now temporary buffers are cached without any thoughts on memory usage!

Depend on #375.

#### Run on 8 GPUs on a DGX-1
Running the [cudf-merge benchmark](https://github.com/rapidsai/ucx-py/pull/375).

| Setup | Wall-clock | Bandwidth | Throughput | Speedup |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| No Buffer | 1.03 s  | 3.97  GB/s  | 24.97 GB/s  |1 |
| Buffer  | 742.74 ms | 5.34 GB/s |  34.47  GB/s  | 1.39  |
| Buffer + IPC_CACHE | 520.30 ms | 8.95 GB/s | **49.47 GB/s** | 1.98  |

<details>
 <summary>Details</summary>

```
$ python  cudf-merge.py -c 100000000 --devs=0,1,2,3,4,5,6,7 --net-devices=auto
cudf merge benchmark
----------------------------
device(s)      | [0, 1, 2, 3, 4, 5, 6, 7]
chunks-per-dev | 1
chunk-size     | 100.00 MB
frac-match     | 0.3
============================
Wall-clock     | 1.03 s
Bandwidth      | 3.97 GB/s
Throughput     | 24.97 GB/s
```
```
$ UCXPY_COMM_BUFFER=y python  cudf-merge.py -c 100000000 --devs=0,1,2,3,4,5,6,7 --net-devices=auto
cudf merge benchmark
----------------------------
device(s)      | [0, 1, 2, 3, 4, 5, 6, 7]
chunks-per-dev | 1
chunk-size     | 100.00 MB
frac-match     | 0.3
============================
Wall-clock     | 742.74 ms
Bandwidth      | 5.34 GB/s
Throughput     | 34.47 GB/s
```
```
$ UCXPY_COMM_BUFFER=y UCX_CUDA_IPC_CACHE=y python  cudf-merge.py -c 100000000 --devs=0,1,2,3,4,5,6,7 --net-devices=auto
cudf merge benchmark
----------------------------
device(s)      | [0, 1, 2, 3, 4, 5, 6, 7]
chunks-per-dev | 1
chunk-size     | 100.00 MB
frac-match     | 0.3
============================
Wall-clock     | 520.30 ms
Bandwidth      | 8.95 GB/s
Throughput     | 49.20 GB/s
```
</details>

### CODE REVIEW

**Comment by Akshay-Venkatesh** [comment]
@madsbk 
Shouldn't you check if `buffer` passed to `tag_send` already belongs to RMM pool? If yes, it has a single registration associated with it anyway and you can avoid the copy overhead to temporary buffer.

**Comment by jakirkham** [comment]
Thanks @madsbk. Very happy to see this implemented and to see it is already helping performance.

**Comment by Akshay-Venkatesh** [comment]
@madsbk Quite possible that solving OOM issues isn't the goal of the PR at all but I'll bring this up anyway.

About the single registration -- I'm not sure how cache.pop() and cache.append() is implemented internally so correct me if I'm mistaken. When the very first attempt is made to send and len of cache is 0, a new DeviceBuffer of size equal to transfer size (nbytes) is requested from RMM. This device buffer could belong to underlying cudaMalloced allocation `alloc_x`. Also the expectation here is that `alloc_x` probably much greater than `nbytes`. This means that all subsequent requests of size `<= alloc_x` can use the same registration as long as `nbytes <= alloc_x` or as long as aggregate message size of concurrent requests <= `alloc_x`. 

When this limit is exceeded either due to concurrency or message size, then I expected len(cache) to return 0 and this results in a new DeviceBuffer(nbytes) call. I believe this may still result in RMM needing a new cudaMalloced allocation `alloc_y` if it's own internal resources are exhausted. For `alloc_y` there would be a new CUDA IPC registration/memory handle associated (which is fine because it's still better than having multiple active handles when `buffer` doesn't belong to RMM). 

My concern is if RMM does cudaFree to cut down memory usage when it notices memory isn't being used as much. The current bug in UCX (https://github.com/rapidsai/ucx-py/issues/370) means that this cudaFree may not actually translate to memory being freed on the GPU because another peer is mapping that memory and it hasn't called close on the memory handle associated with it.  If this is the case, unfortunately using temporary buffers still doesn't solve the OOM issue in https://github.com/rapidsai/ucx-py/issues/370 

@kkraus14 @quasiben @pentschev thoughts on this?

**Comment by madsbk** [comment]
> @madsbk
> Shouldn't you check if `buffer` passed to `tag_send` already belongs to RMM pool? If yes, it has a single registration associated with it anyway and you can avoid the copy overhead to temporary buffer.

Is this true if the buffer was previously registered for communication with another GPU? That will result in a new CUDA IPC registration right?

**Comment by Akshay-Venkatesh** [comment]
There's just one unique handle for every cudaMalloced region actually.

**Comment by jakirkham** [comment]
Well there are a few things to take into account.

1. RMM can be run will pool mode on/off
2. RMM may have multiple pools (due to growth)

Given these, I'm not sure if simply assuming RMM is around is sufficient.

**Comment by quasiben** [comment]
@Akshay-Venkatesh I believe what you have outlined is good summary and correct.  New allocations will be triggered when the buffer is greater than size of the current transfer buffer _and_ UCX will still hold a mapping to the previous buffer where `cudaFree` calls on the exporter will not remove the memory.  

I don't think this work was done to resolve the OOM issues we were seeing but it is a compelling technique to potentially assist in that effort (similar to what you described HPC folks doing -- reserve scratch space for communication buffers).

**Comment by madsbk** [comment]
Now that RMM and UCX is begging to play nice, we don't need this anymore.

**Pull request closed without merging**
