### PR TITLE
[REVIEW] Install dependencies via meta package

### PR DESCRIPTION
**Pull request by raydouglass**
Install dependencies via `rapids-build-env` (which is pre-installed in the containers).

This brings the repo in line with https://docs.rapids.ai/maintainers/depmgmt/

Depends on https://github.com/rapidsai/integration/pull/49

### CODE REVIEW

**Comment by quasiben** [comment]
I think this only passes after rapidsai/integration#49 is merged in.  I believe now it is picking up `autoconf/automake`  from the system instead of from conda-forge

**Comment by jakirkham** [comment]
Should `ucx-py` be [listed in the build package]( https://github.com/rapidsai/integration/blob/f14f5c900fcb02ae5e43b180af3bf6b566f9a776/conda/recipes/rapids-build-env/meta.yaml#L122 ) if that package is being installed here?

**Comment by raydouglass** [comment]
> Should `ucx-py` be [listed in the build package](https://github.com/rapidsai/integration/blob/f14f5c900fcb02ae5e43b180af3bf6b566f9a776/conda/recipes/rapids-build-env/meta.yaml#L122) if that package is being installed here?

I forgot we did that. Thanks, I'll close this PR.

**Comment by jakirkham** [comment]
Would it make sense to drop `ucx-py` from the package and let others install in their CI as needed? This does seem like a nice improvement.

**Pull request closed without merging**
