### PR TITLE
Use __dealloc__ for TopologicalDistance Cython code

### LINKED ISSUE #365: Avoiding `__del__` in `TopologicalDistance`
Noticed that we are using [`__del__` in the `TopologicalDistance`]( https://github.com/rapidsai/ucx-py/blob/eba981f3e486d4d7305eba5e54b13c11c499e303/ucp/_libs/topological_distance.pyx#L28-L30 ). However this isn't supported for extension types (snippet from the docs below).

> **Note:** There is no `__del__()` method for extension types.

ref: https://cython.readthedocs.io/en/latest/src/userguide/special_methods.html#finalization-method-dealloc

### PR DESCRIPTION
**Pull request by pentschev**
Fix #365

### CODE REVIEW

**Comment by pentschev** [comment]
@jakirkham should address #365, let me know if there are any concerns.

**Comment by jakirkham** [comment]
Looks good. Do we know what the CI failure is?

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
> Looks good. Do we know what the CI failure is?

Not sure, but I've seen similar errors to this in dask-cuda recently. I think they're related to a timeout, perhaps it's too short for that test.

**Comment by pentschev** [comment]
There have been some errors that were only reproducible when running all tests, choosing such tests individually would not cause the tests to fail.

**Comment by pentschev** [comment]
Has CI been failing recently or are those errors just showing up because I'm lucky? Both runs failed with different failures and both unrelated to this PR.

**Comment by quasiben** [comment]
I don't know why this is failing either.  I've tried with an updated env and the tests pass locally.  i'll rerun again and see what happens

**Comment by quasiben** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks @pentschev and @quasiben! 😄

**Pull request merged**
