### PR TITLE
Add NVTX annotations

### PR DESCRIPTION
**Pull request by pentschev**
NVTX annotations add a new row `ucxpy` to profiles, identifying `send`/`recv`/`progress` calls. See example below:

Screenshot 2020-04-14 at 18 40 44

### CODE REVIEW

**Comment by pentschev** [comment]
Note that in UCX we can enqueue send/recv tasks, but we have then to call `ucp_worker_progress` to ensure transfer. This is pretty much like CUDA async behavior, but we don't have the granularity to see what exactly happens under-the-hood with UCX. I'm not sure whether `send`/`recv` ranges are useful at all for the profiles here, certainly seeing that the progress task takes pretty much the entire time will reduce our ability to understand the profiles, but I don't think there's much we can do from UCX-Py since `ucp_worker_progress` doesn't return more information w.r.t. the transfers being executed.

**Comment by quasiben** [comment]
cc @jrhemstad @kkraus14

**Comment by jrhemstad** [comment]
> Note that in UCX we can enqueue send/recv tasks, but we have then to call `ucp_worker_progress` to ensure transfer. This is pretty much like CUDA async behavior, but we don't have the granularity to see what exactly happens under-the-hood with UCX. I'm not sure whether `send`/`recv` ranges are useful at all for the profiles here, certainly seeing that the progress task takes pretty much the entire time will reduce our ability to understand the profiles, but I don't think there's much we can do from UCX-Py since `ucp_worker_progress` doesn't return more information w.r.t. the transfers being executed.

Sure, this makes sense. How much effort would it be to to annotate Dask send/receive directly? I'm not suggesting doing it in mainline Dask, but just in a custom branch for profiling purposes.

**Comment by jakirkham** [comment]
Dask just calls `_Endpoint`'s `send` and `recv` methods. So this is doing what you suggest.

**Comment by jakirkham** [comment]
What's the overhead of these annotations typically?

**Comment by pentschev** [comment]
> Dask just calls _Endpoint's send and recv methods. So this is doing what you suggest.

Exactly, this PR annotates directly what Dask calls in UCX-Py.

**Comment by pentschev** [comment]
> What's the overhead of these annotations typically?

This is also something @quasiben and I discussed offline just an hour ago or so. My assumption is that these will be completely disabled if you're not running the process with nsys, is that correct @jrhemstad ?

**Comment by kkraus14** [comment]
> > What's the overhead of these annotations typically?
> 
> This is also something @quasiben and I discussed offline just an hour ago or so. My assumption is that these will be completely disabled if you're not running the process with nsys, is that correct @jrhemstad ?

Yes, if nsys isn't connected the calls become no-ops under the hood. On the Python side we cache the domain currently, but aren't caching the message yet. In general, these calls are designed to be as light weight and efficient as possible.

**Comment by pentschev** [comment]
Thanks @kkraus14 for details!

**Comment by quasiben** [comment]
Thanks @pentschev

**Pull request merged**
