### PR TITLE
Use PyNVML 12

### PR DESCRIPTION
**Pull request by jakirkham**
Bump `pynvml` from `11` to `12`. This version of `pynvml` also now depends on `nvidia-ml-py` for core functionality.

### CODE REVIEW

**Review by jameslamb — APPROVED** [review]
Makes sense to me, based on my understanding of https://github.com/gpuopenanalytics/pynvml/pull/57

**Review by pentschev — APPROVED** [review]
LGTM. Thanks @jakirkham

**Comment by jakirkham** [comment]
Thanks James and Peter! 🙏

**Comment by jakirkham** [comment]
Fixed issue: https://github.com/rapidsai/ucx-py/issues/928

**Pull request merged**
