### PR TITLE
Remove docs on using UCX-Py with Dask

### PR DESCRIPTION
**Pull request by pentschev**
This became redundant and is now better documented in Dask-CUDA's docs under https://docs.rapids.ai/api/dask-cuda/nightly/

### CODE REVIEW

**Review by madsbk — APPROVED** [review]
Looks good

**Comment by pentschev** [comment]
Thanks @madsbk !

**Comment by pentschev** [comment]
rerun tests

**Comment by pentschev** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Pull request merged**
