### PR TITLE
Install `libnuma` on RTD

### PR DESCRIPTION
**Pull request by jakirkham**
Uses the functionality recently added to RTD in PR ( https://github.com/readthedocs/readthedocs.org/pull/8065 ) by following [this example]( https://github.com/readthedocs/test-builds/blob/defb3a646080eb330eb65f935e414fd1e7b602b1/.readthedocs.yaml#L6-L7 ) to install `libnuma` on RTD.

### CODE REVIEW

**Comment by pentschev** [comment]
Nice!

**Comment by jakirkham** [comment]
JFYI RTD needs to still deploy the change on their end, which is scheduled for next Tuesday afternoon ( https://github.com/readthedocs/readthedocs.org/pull/8065#issuecomment-839998356 ).

Also this feature requires adopting a new RTD config spec version ( https://github.com/readthedocs/readthedocs.org/pull/8065#issuecomment-840002763 ). So have made those changes above and [confirmed those work]( https://readthedocs.org/projects/ucx-py/builds/13749521/ ) before adding `apt` packages. The last commit adds the `apt` packages, which won't work for now, but should work next week (as noted above).

**Comment by pentschev** [comment]
Sure, let's wait for that. Thanks @jakirkham for this! 😄

**Comment by jakirkham** [comment]
Looks like RTD has deployed the change. Build is running. Let's see how it goes 🙂

**Comment by jakirkham** [comment]
Looks like it worked! 🎉

Screen Shot 2021-05-18 at 10 18 41 AM

**Comment by quasiben** [comment]
Thanks @jakirkham !

**Review by quasiben — APPROVED** [review]

**Comment by quasiben** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
I don't think the bot works on this repo yet. So went ahead and merged manually (since it seems like we are ok with the changes)

**Comment by pentschev** [comment]
Thanks @jakirkham , great work! 😄

**Comment by jakirkham** [comment]
RTD shared this as an example use case in [their recent blogpost on this new feature]( https://blog.readthedocs.com/apt-packages/ ).

**Pull request merged**
