### PR TITLE
Run more Distributed UCX tests on CI

### PR DESCRIPTION
**Pull request by jakirkham**
Includes the RMM tests and slow UCX tests from Distributed as well.

### CODE REVIEW

**Comment by pentschev** [comment]
@jakirkham I'm not sure where `--runslow` comes from, but it seems it failed on that: https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-gpu-build/detail/ucx-py-gpu-build/1549/pipeline#log-2158 .

**Comment by jakirkham** [comment]
It comes [from Distributed]( https://github.com/dask/distributed/blob/b8a0b8e110d37b7986d0693e9f35fdddb85ded17/conftest.py#L25-L32 ). Any tests decorated with `@pytest.mark.slow` like [this one]( https://github.com/dask/distributed/blob/2a795df67d3521dbfbf49a650238bab7266a86ee/distributed/comm/tests/test_ucx.py#L231 ) will be skipped unless `--runslow` is passed as a CLI option.

It does look like 1 of the 3 GPU test jobs failed. However it doesn't actually show a test failure AFAICT. Do you see one? Assuming there isn't one and will schedule a CI rerun. Though please let me know if I missed something.

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
I see an error from UCX-Py in [this run]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-gpu-build/detail/ucx-py-gpu-build/1553/ ). Though that's unrelated to this change.

```
tests/test_guarantee_msg_order.py::test_mismatch ERROR Ignored except: <class 'ValueError'> Both peers must set guarantee_msg_order identically
ERROR Ignored except: <class 'ValueError'> Both peers must set guarantee_msg_order identically
```

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Starting a new trivial change job to figure out why that error shows up. ( https://github.com/rapidsai/ucx-py/pull/475 )

**Comment by jakirkham** [comment]
Though now I also realize this is probably what you are referring to. So it seems like Distributed's `conftest.py` is not being picked up for some reason.

```bash
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --runslow
  inifile: None
  rootdir: /conda/envs/gdf/lib/python3.7/site-packages/distributed/comm/tests
```

**Comment by jakirkham** [comment]
Have pushed a fix to just run the slow marked tests separately. Didn't know a good way to include the slow marked tests with regular tests. Asked [this SO question]( https://stackoverflow.com/q/60998990/ ) to see if there is a way to include both in the same run.

**Comment by jakirkham** [comment]
rerun tests

(appears we had some HTTP issues downloading Conda packages)

**Comment by quasiben** [comment]
@ajschmidt8  you may have to be the one to merge this in.   I don't seem to have access

**Comment by pentschev** [comment]
I was able to merge, maybe was just GH acting weird @quasiben .

**Comment by quasiben** [comment]
Thanks @pentschev

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
