### PR TITLE
Update black to 22.3.0

### PR DESCRIPTION
**Pull request by charlesbluca**
Looks like the version of Black we were using broke due to a change in click (xref https://github.com/psf/black/issues/2963) - this PR bumps us to the latest version, which resolves those issues (and makes some minor styling changes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Think the issue is this is still using the 22.04 Docker image when we want the 22.06 one. Asked offline for help moving to the latest image.

**Comment by charlesbluca** [comment]
Would we also want to backport this change to `branch-0.25`? cc @pentschev

**Comment by jakirkham** [comment]
At least in the 22.04/0.25 release we pin `black` to [an older version]( https://github.com/rapidsai/integration/blob/64b7afc08aff0c11127ccdef93ccaf8a53f1ebc6/conda/recipes/versions.yaml#L31-L32 ), so this won't work there. In 22.06/0.26, this [newer version of `black` is used]( https://github.com/rapidsai/integration/blob/b2e607aa52b9fc5147e3995a2c1b55244fc17926/conda/recipes/versions.yaml#L31-L32 ).

**Comment by jakirkham** [comment]
rerun tests

**Review by jakirkham — APPROVED** [review]

**Review by pentschev — APPROVED** [review]
Looks great, thanks @charlesbluca !

**Comment by pentschev** [comment]
@gpucibot merge

**Pull request merged**
