### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by quasiben**
PR adds sphinx documentation

You can see an example running here:
https://quasiben.github.io/ucx-py/

I am working on RTD as well

### CODE REVIEW

**Comment by quasiben** [comment]
RTD is up: 
https://ucx-py.readthedocs.io/en/latest/

**Comment by madsbk** [comment]
Nice!

**Comment by jakirkham** [comment]
Are we able to build the docs as part of gpuCI, @raydouglass? 🙂

**Comment by jakirkham** [comment]
FWIW we can also enable [ReadTheDocs PR builds]( https://blog.readthedocs.com/building-docs-for-pull-requests/ ).

**Comment by quasiben** [comment]
@madsbk @jakirkham what do you think about merging in this PR as is the iterating with subsequent PRs ?

**Comment by jakirkham** [comment]
Seems fine to me.

Would be nice if we could build the docs on CI (just to make sure it continues to work with later changes), but we can raise an issue on this if we don't know how to do that.

**Comment by quasiben** [comment]
@jakirkham i need an approval when you have a minute

**Comment by quasiben** [comment]
thanks!

**Comment by jakirkham** [comment]
Thanks for adding this 🙂

**Comment by jakirkham** [comment]
> Would be nice if we could build the docs on CI (just to make sure it continues to work with later changes), but we can raise an issue on this if we don't know how to do that.

Raised issue ( https://github.com/rapidsai/ucx-py/issues/278 ) on this point.

**Pull request merged**
