### PR TITLE
WIP: Mark C level functions as `nogil`

### PR DESCRIPTION
**Pull request by jakirkham**
These functions should be safe to use without the Python GIL as they are not creating or destroying Python objects. So mark them as such.

Note: This does **not** actually release the GIL. We still have to do that ourselves. However this allows us to use these in code sections where we have already released the GIL. We can also continue to use them when we have the GIL as well.

### CODE REVIEW

**Comment by quasiben** [comment]
Thansk @jakirkham .  Looks like CI is failing with legitimate errors:

> ucp/_libs/send_recv.pyx:90:51: Cannot assign type 'void (void *, ucs_status_t)' to 'ucp_send_callback_t'

**Comment by jakirkham** [comment]
Yeah that should be fixed by PR ( https://github.com/rapidsai/ucx-py/pull/390 ).

**Comment by jakirkham** [comment]
Even though this passes. We should hold off on merging for a bit as there are some warning. These highlight some additional changes we need.

From [the log]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci%2Fucx-py%2Fprb%2Fucx-py-gpu-build/detail/ucx-py-gpu-build/1054/pipeline/ ) we can see the following warnings:

```
warning: ucp/_libs/send_recv.pyx:85:40: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: ucp/_libs/send_recv.pyx:132:8: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: ucp/_libs/send_recv.pyx:148:40: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: ucp/_libs/send_recv.pyx:195:8: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: ucp/_libs/core.pyx:353:12: Casting a GIL-requiring function into a nogil function circumvents GIL validation
warning: ucp/_libs/core.pyx:424:12: Casting a GIL-requiring function into a nogil function circumvents GIL validation
```

This is happening because the C functions potentially may not hold the GIL when calling our Cython callbacks. We can fix this by defining our Cython callbacks to also not hold the GIL, but acquire it internally when it is needed.

Will make some changes to this affect in a second.

**Comment by jakirkham** [comment]
To fix the warnings, it makes to type our callbacks as `nogil`. However as we still need the `gil` within the callbacks, we need to acquire the GIL internally. This means we should also release the GIL before calling into C functions. Given all of this, it makes more sense to start a new PR that covers these as well. Have added PR ( https://github.com/rapidsai/ucx-py/pull/391 ).

**Pull request closed without merging**
